services:
  # postgres
  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      TZ: Asia/Qyzylorda
    volumes:
      - ./script/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d applications'" ]
      interval: 10s
      timeout: 60s
      retries: 20
  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "44047:8080"

  # kafka
  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KFK_BROKERS:-broker\:29092},PLAINTEXT_HOST://${KFK_BROKERS:-broker\:9092}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD-SHELL", "nc -zv broker 9092" ]
      interval: 10s
      timeout: 60s
      retries: 20

  # app
  app:
    build: .
    container_name: app
    image: gorm_kafka_docker_app
    ports:
      - "${SRV_PORT:-44049}:${SRV_PORT:-44049}"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-applications}
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      DB_TZ: ${DB_TZ:-Asia/Qyzylorda}
      DB_SSL: ${DB_SSL:-disable}
      SRV_HOST: ${SRV_HOST:-localhost}
      SRV_PORT: ${SRV_PORT:-44049}
      KFK_BROKERS: ${KFK_BROKERS:-broker\:9092}
      KFK_TOPIC: ${KFK_TOPIC:-applications}
      KFK_GROUPID: ${KFK_GROUPID:-applications}
      KFK_LOCAL: ${KFK_LOCAL:-true}
      KFK_USER: ${KFK_USER}
      KFK_PWD: ${KFK_PWD}
